### PR TITLE
llvm-test-suite: Enabled parallel compilation and added AA target

### PR DESCRIPTION
**Pull request by sjalander**
The test suite has been changed to use `nproc` threads instead of a single thread during compilation.

Also added an alias analysis build and run target.

### CODE REVIEW

**Comment by sjalander** [comment]
Seems like it has a significant speed improvement with llvm-test-suite finishing in 6 minutes now

**Comment by sjalander** [comment]
Now also bumps jlm and adds -Jred to the default optimizations for the llvm-test-suite used by jlm's CI.

**Comment by phate** [comment]
This change will result in several instances of jlm-opt running in parallel, right?

**Comment by sjalander** [comment]
Yes, it will compile multiple tests in parallel.
I've run it multiple times without encountering any issues.

**Comment by sjalander** [comment]
The llvm-test-suite definitely has multiple c-files with the same name.
So I guess this could become an issue with jlm-opt.

**Comment by phate** [comment]
I will hold back on this PR until the problem of the non-unique intermediate files is resolved. I created an [issue](https://github.com/phate/jlm/issues/312) on it in jlm and will attend to it asap.

**Review by phate — APPROVED** [review]
LGTM

**Pull request merged**
